# DATABASE
spring.data.mongodb.uri=${MONGO_CONNECTION_STRING}
spring.data.mongodb.database=${MONGO_DATABASE}

# FILE UPLOAD
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# OPENAPI / SWAGGER
# OpenAPI JSON at /v3/api-docs, Swagger UI at /docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/docs
